### ISSUE TITLE
`--group` and `--exclude-group` do not work

### ISSUE THREAD

**Issue by dvdoug** [sebastianbergmann/phpunit#5393]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.2-dev
| PHP version         | 8.2.6
| Installation Method | Composer

#### Summary

PHPUnit crashes when running `phpunit --exclude-group=something`

Examples: 

#### Current behavior

```
PHPUnit 10.2-dev by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.6
Configuration: /home/runner/work/BoxPacker/BoxPacker/phpunit.xml



An error occurred inside PHPUnit.

Message:  Too few arguments to function PHPUnit\Runner\Filter\GroupFilterIterator::__construct(), 1 passed and exactly 3 expected
Location: /home/runner/work/BoxPacker/BoxPacker/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:68

#0 /home/runner/work/BoxPacker/BoxPacker/vendor/phpunit/phpunit/src/TextUI/Application.php(168): PHPUnit\TextUI\TestRunner->run()
#1 /home/runner/work/BoxPacker/BoxPacker/vendor/phpunit/phpunit/phpunit(99): PHPUnit\TextUI\Application->run()
#2 {main}

Caused by: /home/runner/work/BoxPacker/BoxPacker/vendor/phpunit/phpunit/src/Runner/Filter/GroupFilterIterator.php:30

#0 [internal function]: PHPUnit\Runner\Filter\GroupFilterIterator->__construct()
#1 /home/runner/work/BoxPacker/BoxPacker/vendor/phpunit/phpunit/src/Event/Value/TestSuite/TestSuiteBuilder.php(55): RecursiveFilterIterator->getChildren()
#2 /home/runner/work/BoxPacker/BoxPacker/vendor/phpunit/phpunit/src/TextUI/TestSuiteFilterProcessor.php(84): PHPUnit\Event\TestSuite\TestSuiteBuilder::from()
#3 /home/runner/work/BoxPacker/BoxPacker/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(57): PHPUnit\TextUI\TestSuiteFilterProcessor->process()
#4 /home/runner/work/BoxPacker/BoxPacker/vendor/phpunit/phpunit/src/TextUI/Application.php(168): PHPUnit\TextUI\TestRunner->run()
#5 /home/runner/work/BoxPacker/BoxPacker/vendor/phpunit/phpunit/phpunit(99): PHPUnit\TextUI\Application->run()
#6 {main}
```

#### How to reproduce

- Clone https://github.com/dvdoug/PHPCoord
- `composer install`
- `vendor/bin/phpunit --exclude-group=integration --no-coverage`

#### Expected behavior

No crash 😄

**Comment by sebastianbergmann** [comment]
This already/also affects PHPUnit 10.1 and can be reproduced using PHPUnit's own test suite:
```
$ ./phpunit --group small
PHPUnit 10.1.3-41-g981b911698 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.6
Configuration: /usr/local/src/phpunit/phpunit.xml

An error occurred inside PHPUnit.

Message:  Too few arguments to function PHPUnit\Runner\Filter\GroupFilterIterator::__construct(), 1 passed and exactly 3 expected
Location: /usr/local/src/phpunit/src/TextUI/TestRunner.php:68

#0 /usr/local/src/phpunit/src/TextUI/Application.php(168): PHPUnit\TextUI\TestRunner->run()
#1 /usr/local/src/phpunit/phpunit(99): PHPUnit\TextUI\Application->run()
#2 {main}

Caused by: /usr/local/src/phpunit/src/Runner/Filter/GroupFilterIterator.php:30

#0 [internal function]: PHPUnit\Runner\Filter\GroupFilterIterator->__construct()
#1 /usr/local/src/phpunit/src/Event/Value/TestSuite/TestSuiteBuilder.php(55): RecursiveFilterIterator->getChildren()
#2 /usr/local/src/phpunit/src/TextUI/TestSuiteFilterProcessor.php(84): PHPUnit\Event\TestSuite\TestSuiteBuilder::from()
#3 /usr/local/src/phpunit/src/TextUI/TestRunner.php(57): PHPUnit\TextUI\TestSuiteFilterProcessor->process()
#4 /usr/local/src/phpunit/src/TextUI/Application.php(168): PHPUnit\TextUI\TestRunner->run()
#5 /usr/local/src/phpunit/phpunit(99): PHPUnit\TextUI\Application->run()
#6 {main}
```
```
$ ./phpunit --exclude-group small
PHPUnit 10.1.3-41-g981b911698 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.6
Configuration: /usr/local/src/phpunit/phpunit.xml

An error occurred inside PHPUnit.

Message:  Too few arguments to function PHPUnit\Runner\Filter\GroupFilterIterator::__construct(), 1 passed and exactly 3 expected
Location: /usr/local/src/phpunit/src/TextUI/TestRunner.php:68

#0 /usr/local/src/phpunit/src/TextUI/Application.php(168): PHPUnit\TextUI\TestRunner->run()
#1 /usr/local/src/phpunit/phpunit(99): PHPUnit\TextUI\Application->run()
#2 {main}

Caused by: /usr/local/src/phpunit/src/Runner/Filter/GroupFilterIterator.php:30

#0 [internal function]: PHPUnit\Runner\Filter\GroupFilterIterator->__construct()
#1 /usr/local/src/phpunit/src/Event/Value/TestSuite/TestSuiteBuilder.php(55): RecursiveFilterIterator->getChildren()
#2 /usr/local/src/phpunit/src/TextUI/TestSuiteFilterProcessor.php(84): PHPUnit\Event\TestSuite\TestSuiteBuilder::from()
#3 /usr/local/src/phpunit/src/TextUI/TestRunner.php(57): PHPUnit\TextUI\TestSuiteFilterProcessor->process()
#4 /usr/local/src/phpunit/src/TextUI/Application.php(168): PHPUnit\TextUI\TestRunner->run()
#5 /usr/local/src/phpunit/phpunit(99): PHPUnit\TextUI\Application->run()
#6 {main}
```

**Comment by sebastianbergmann** [comment]
This looks like it is caused by 08ac84ce417db6ff61c072f87d22da060750976c.

**Comment by sebastianbergmann** [comment]
We only have end-to-end tests for the `--group` and `--exclude-group` options where the test runner is invoked with an argument. We are missing tests for these options where the test runner is invoked without an argument.
