### ISSUE TITLE
PHP signature bug when updating from 9.6.12 to 9.6.13

### ISSUE THREAD

**Issue by COil** [sebastianbergmann/phpunit#5527]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.6.13
| PHP version         | 7.4.33
| Installation Method | Composer

#### Summary

A bug occurs when updating from PHPUnit `9.6.12` to `9.6.13` which seems to be a BC. 

#### Current behavior

```
root@docker:/apps/my-app# vendor/bin/simple-phpunit
PHPUnit 9.5.28 by Sebastian Bergmann and contributors.

Testing
Too few arguments to function PHPUnit\Util\PHP\AbstractPhpProcess::runTestJob(), 3 passed in /apps/my-app/http-api/vendor/bin/.phpunit/phpunit-9.5-0/src/Framework/TestCase.php on line 903 and exactly 4 expected

Remaining indirect deprecation notices (3)
```

#### How to reproduce

    "require-dev": {
        "phpunit/phpunit": "v9.6.12",

It happens on all tests when using this version.

#### Expected behavior

No error.

**Comment by sebastianbergmann** [comment]
You write that you are updating from PHPUnit 9.6.12 to PHPUnit 9.6.13, yet your output says you are using PHPUnit 9.5.28.

It also appears that you are not using PHPUnit directly, but rather a third-party wrapper around it (`simple-phpunit`).

**Comment by COil** [comment]
Hello Sebastian, I can confirm I don't have the bug when using `phpunit` instead of `simple-phpunit`. Thanks for the feedback.
