### ISSUE TITLE
Data Providers cannot be generators anymore

### ISSUE THREAD

**Issue by thanosp** [sebastianbergmann/phpunit#2380]
I've just updated my project to 5.7 and immediately a certain category of tests broke.
All of them were using yield in data providers. 
Maybe it was never officially supported but it was handy especially for constructing "bad input" out of a single source of "good input".
I only see the feature to 'Add support for multiple data providers' (#2223) as possibly related in the changelog.

My sample test case:
```
<?php
declare(strict_types=1);

use PHPUnit\Framework\TestCase;

class GeneratorTest extends TestCase
{
    /**
     * @dataProvider generatorData
     * @param $data
     */
    public function testGeneratorProvider($data)
    {
        $this->assertNotEmpty($data);
    }

    /**
     * @return Generator
     */
    public function generatorData(): Generator
    {
        yield 'testing';
    }
}
```

**Comment by sebastianbergmann** [comment]
@borela Can you please have a look at this? Thanks!

**Comment by sebastianbergmann** [comment]
@thanosp Your example does not work with PHPUnit 5.6:
```
$ phpunit GeneratorTest
PHPUnit 5.6.8 by Sebastian Bergmann and contributors.

W                                                                   1 / 1 (100%)

Time: 39 ms, Memory: 4.00MB

There was 1 warning:

1) Warning
The data provider specified for GeneratorTest::testGeneratorProvider is invalid.
Data set #0 is invalid.

WARNINGS!
Tests: 1, Assertions: 0, Warnings: 1.
```

**Comment by sebastianbergmann** [comment]
@thanosp Your example works with PHPUnit 5.6 when I change `yield 'testing';` to `yield ['testing'];`.

**Comment by sebastianbergmann** [comment]
## Reproducing Example
```php
<?php
use PHPUnit\Framework\TestCase;

class Test extends TestCase
{
    /**
     * @dataProvider generatorData
     */
    public function testGeneratorProvider($data)
    {
        $this->assertNotEmpty($data);
    }

    /**
     * @return Generator
     */
    public function generatorData()
    {
        yield ['testing'];
    }
}
```
## Actual Output
```
PHPUnit 5.7.0 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 40 ms, Memory: 4.00MB

There was 1 error:

1) Test::testGeneratorProvider
ArgumentCountError: Too few arguments to function Test::testGeneratorProvider(), 0 passed and exactly 1 expected

/home/sb/Test.php:9

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```
## Expected Output
```
PHPUnit 5.7.0 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 28 ms, Memory: 4.00MB

OK (1 test, 1 assertion)
```

**Comment by borela** [comment]
@sebastianbergmann I created a pull request, the test you added passed with that patch, the issue was that [generators were being skipped](https://github.com/sebastianbergmann/phpunit/pull/2381/commits/4dcb2c8623526d86236beba1a2942124e7e794ee#diff-d2b0b699e9f0cfd6bd35cb3338167223R479).
